version: '3'

services:
  ingestor:
    image: nytingestortest
    restart: always
    environment:
      - NYT_API_KEY
      - POSTGRES_PASSWORD
      - POSTGRES_USER
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=root
    ports:
      - "8001:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 30s
      retries: 10
